version: "3.4"

services:
  notebook:
    build:
      context: ./
    volumes:
      - ./:/app
    environment:
      - DEEPGRAM_API_KEY
      - OPENAI_API_KEY
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --reload --ws-max-size 10485760 --ws-ping-timeout 300"
